version: '3'
services:
  user_service:
    build: ./services/user_service
    ports: 
      - "5002:5000"
    networks:
      - mynetwork

  post_service:
    build: ./services/post_service
    ports:
      - "5001:5000"
    networks:
      - mynetwork
      
  comment_service:
    build: ./services/comment_service
    ports:
      - "5003:5000"
    networks:
      - mynetwork

networks:
  mynetwork:
